apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanuj-kumar-deploy
  labels:
    app: thanuj-kumar-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thanuj-kumar-app
  template:
    metadata:
      labels:
        app: thanuj-kumar-app
    spec:
      containers:
      - name: thanuj-kumar-container
        image: thanujkumar/thanuj-kumar-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: thanuj-kumar-np-service
  labels:
    app: thanuj-kumar-app
spec:
  selector:
    app: thanuj-kumar-app

  type: NodePort
  ports:
  - nodePort: 31002
    port: 8080
    targetPort: 8080
