#Service Type nodePort
apiVersion: v1
kind: Service
metadata:
  name: thanuj-kumar-np-service
  labels:
    app: thanuj-kumar-app
spec:
  selector:
    app: thanuj-kumar-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
